'use client';
import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {Button} from '../../components/ui/button';
import {Input} from '../../components/ui/input';
import {Textarea} from '../../components/ui/textarea';
import {copyGroups,type SiteContent,type Photo,type Place} from '../../content/model';

type Props={initialContent:SiteContent;initialRevision:number};
function Field({label,value,onChange,multiline=false,type='text'}:{label:string;value:string|number;onChange:(s:string)=>void;multiline?:boolean;type?:string}){return <label className="editor-field"><span>{label}</span>{multiline?<Textarea value={value} onChange={e=>onChange(e.target.value)}/>:<Input type={type} step={type==='number'?'any':undefined} value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
async function uploadPhoto(file:File):Promise<Photo>{
 if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Choose a JPEG, PNG, or WebP photo.');
 if(file.size>25*1024*1024)throw new Error('Choose a photo smaller than 25 MB.');
 // Re-encode on the device to limit upload size and remove embedded location metadata.
 const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>60000000){bitmap.close();throw new Error('This photo is too large. Export a smaller copy first.');}
 const scale=Math.min(1,2400/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const context=canvas.getContext('2d');if(!context){bitmap.close();throw new Error('Photo processing is unavailable in this browser.');}context.fillStyle='#ffffff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Could not prepare this photo.')),'image/jpeg',.88));
 const response=await fetch('/api/uploads',{method:'POST',headers:{'Content-Type':'image/jpeg'},body:blob});const data=await response.json() as {src:string;error?:string};if(!response.ok)throw new Error(data.error||'Upload failed.');return {src:data.src,alt:'',caption:''};
}
function PhotoEditor({photo,onChange,showCaption=true}:{photo:Photo;onChange:(photo:Photo)=>void;showCaption?:boolean}){return <div className="photo-edit"><img src={photo.src} alt={photo.alt||'Uploaded photo preview'}/><div><Field label="Photo description (required)" value={photo.alt} onChange={alt=>onChange({...photo,alt})}/>{showCaption&&<Field label="Caption" value={photo.caption||''} onChange={caption=>onChange({...photo,caption})}/>}</div></div>}
function Upload({label,onUpload,onBusy,onError,multiple=false}:{label:string;onUpload:(photos:Photo[])=>void;onBusy:(busy:boolean)=>void;onError:(message:string)=>void;multiple?:boolean}){
 const [busy,setBusy]=useState(false);return <label className="upload-control"><span>{busy?'Uploading photos…':label}</span><input aria-label={label} type="file" accept="image/jpeg,image/png,image/webp" multiple={multiple} disabled={busy} onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;setBusy(true);onBusy(true);onError('');const completed:Photo[]=[];try{for(const file of files)completed.push(await uploadPhoto(file));}catch(error){onError(error instanceof Error?error.message:'Upload failed.');}finally{if(completed.length)onUpload(completed);setBusy(false);onBusy(false);}}}/></label>
}
export default function Editor({initialContent,initialRevision}:Props){
 const [content,setContent]=useState(initialContent);const [revision,setRevision]=useState(initialRevision);const [saved,setSaved]=useState(JSON.stringify(initialContent));const [saving,setSaving]=useState(false);const [uploads,setUploads]=useState(0);const [message,setMessage]=useState('');const [error,setError]=useState('');const dirty=JSON.stringify(content)!==saved;
 const onBusy=(busy:boolean)=>setUploads(n=>n+(busy?1:-1));
const draftRef=useRef(content);draftRef.current=content;
 useEffect(()=>{type Context={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};const context=(document as Document&{modelContext?:Context}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
 const register=(tool:Parameters<Context['registerTool']>[0])=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* Optional browser API. */}};
 register({name:'read_site_editor',description:'Read the site text currently staged in the owner editor.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({copy:draftRef.current.copy})});
 register({name:'stage_site_text',description:'Stage text changes in the owner editor. Does not save or publish; use Save changes in the editor to apply.',inputSchema:{type:'object',properties:{field:{type:'string',enum:Object.keys(initialContent.copy)},text:{type:'string',maxLength:10000}},required:['field','text'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const value=input as {field?:unknown;text?:unknown};if(!value||typeof value.field!=='string'||!Object.hasOwn(draftRef.current.copy,value.field)||typeof value.text!=='string'||value.text.length>10000)throw new Error('Choose a valid text field and text of at most 10,000 characters.');const field=value.field as keyof SiteContent['copy'];const text=value.text;flushSync(()=>setContent(c=>({...c,copy:{...c.copy,[field]:text}})));return {field,text,saved:false};}});
 return()=>lifecycle.abort();},[]);
 useEffect(()=>{if(!dirty&&!uploads)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,uploads]);
 async function save(){setSaving(true);setError('');setMessage('');const snapshot=JSON.stringify(content);try{const response=await fetch('/api/content',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,revision})});const result=await response.json() as {revision:number;error?:string};if(!response.ok)throw new Error(result.error||'Could not save.');setRevision(result.revision);setSaved(snapshot);setMessage('Saved. Your changes are now on the site.');}catch(error){setError(error instanceof Error?error.message:'Could not save. Your edits are still here.');}finally{setSaving(false);}}
 function trip(index:number,changes:Partial<Place>){setContent(c=>({...c,places:c.places.map((p,i)=>i===index?{...p,...changes}:p)}));}
 return <div className="editor"><header className="editor-top"><div><h1>Edit your site</h1><p>Update your text and photos, then save to put your changes on the site.</p></div><a href="/" target="_blank" rel="noreferrer" className="text-link">View site</a></header><div className="editor-save"><Button className="save-button" disabled={saving||uploads>0||!dirty} onClick={save}>{saving?'Saving…':uploads?'Uploading…':'Save changes'}</Button><span role="status">{message&&!dirty?message:dirty?'You have unsaved changes.':'All changes saved.'}</span></div>{error&&<p className="editor-error" role="alert">{error}</p>}<nav className="editor-nav" aria-label="Editor sections"><a href="#text">Page text</a><a href="#portrait">Portrait</a><a href="#courses">Coursework</a><a href="#projects">Projects</a><a href="#travel">Travel albums</a></nav>
 <fieldset disabled={saving||uploads>0} className="editor-body"><section id="text"><h2>Page text</h2>{copyGroups.map(([title,fields])=><details className="editor-section" key={title} open={title==='Home'}><summary>{title}</summary><div className="editor-grid">{fields.map(([key,label])=><Field key={key} label={label} multiline={['bio','summary'].includes(key)||key.endsWith('Description')} value={content.copy[key]} onChange={value=>{setMessage('');setContent(c=>({...c,copy:{...c.copy,[key]:value}}));}}/>)}</div></details>)}</section>
 <section id="portrait" className="editor-section"><h2>Your portrait</h2><p>JPEG, PNG, or WebP. Photos are resized for the web.</p>{content.portrait&&<><PhotoEditor showCaption={false} photo={content.portrait} onChange={portrait=>setContent(c=>({...c,portrait}))}/><Button variant="outline" onClick={()=>setContent(c=>({...c,portrait:null}))}>Remove portrait</Button></>}<Upload label={content.portrait?'Replace portrait':'Add portrait'} onBusy={onBusy} onError={setError} onUpload={photos=>setContent(c=>({...c,portrait:photos[0]}))}/></section>
 <section id="courses" className="editor-section"><h2>School & coursework</h2>{content.courses.map((course,i)=><div className="entry-edit" key={i}><h3>Course {i+1}</h3><div className="editor-grid"><Field label="Course code" value={course.code} onChange={code=>setContent(c=>({...c,courses:c.courses.map((p,n)=>n===i?{...p,code}:p)}))}/><Field label="Course title" value={course.title} onChange={title=>setContent(c=>({...c,courses:c.courses.map((p,n)=>n===i?{...p,title}:p)}))}/><Field label="Description" multiline value={course.description} onChange={description=>setContent(c=>({...c,courses:c.courses.map((p,n)=>n===i?{...p,description}:p)}))}/><Field label="Coursework link (optional)" type="url" value={course.url||''} onChange={url=>setContent(c=>({...c,courses:c.courses.map((p,n)=>n===i?{...p,url}:p)}))}/></div>{course.photo&&<><PhotoEditor photo={course.photo} onChange={photo=>setContent(c=>({...c,courses:c.courses.map((p,n)=>n===i?{...p,photo}:p)}))}/><Button variant="outline" onClick={()=>setContent(c=>({...c,courses:c.courses.map((p,n)=>n===i?{...p,photo:null}:p)}))}>Remove photo</Button></>}<Upload label="Add or replace course photo" onBusy={onBusy} onError={setError} onUpload={photos=>setContent(c=>({...c,courses:c.courses.map((p,n)=>n===i?{...p,photo:photos[0]}:p)}))}/><Button variant="outline" onClick={()=>setContent(c=>({...c,courses:c.courses.filter((_,n)=>n!==i)}))}>Remove course</Button></div>)}<Button variant="outline" onClick={()=>setContent(c=>({...c,courses:[...c.courses,{code:'',title:'',description:'',url:''}]}))}>Add course</Button></section>
 <section id="projects" className="editor-section"><h2>Projects</h2>{content.projects.map((project,i)=><div className="entry-edit" key={i}><h3>Project {i+1}</h3><div className="editor-grid"><Field label="Project title" value={project.title} onChange={title=>setContent(c=>({...c,projects:c.projects.map((p,n)=>n===i?{...p,title}:p)}))}/><Field label="Project link (optional)" type="url" value={project.url||''} onChange={url=>setContent(c=>({...c,projects:c.projects.map((p,n)=>n===i?{...p,url}:p)}))}/><Field label="Description" multiline value={project.description} onChange={description=>setContent(c=>({...c,projects:c.projects.map((p,n)=>n===i?{...p,description}:p)}))}/></div>{project.photo&&<><PhotoEditor photo={project.photo} onChange={photo=>setContent(c=>({...c,projects:c.projects.map((p,n)=>n===i?{...p,photo}:p)}))}/><Button variant="outline" onClick={()=>setContent(c=>({...c,projects:c.projects.map((p,n)=>n===i?{...p,photo:null}:p)}))}>Remove photo</Button></>}<Upload label="Add or replace project photo" onBusy={onBusy} onError={setError} onUpload={photos=>setContent(c=>({...c,projects:c.projects.map((p,n)=>n===i?{...p,photo:photos[0]}:p)}))}/><Button variant="outline" onClick={()=>setContent(c=>({...c,projects:c.projects.filter((_,n)=>n!==i)}))}>Remove project</Button></div>)}<Button variant="outline" onClick={()=>setContent(c=>({...c,projects:[...c.projects,{title:'',description:'',url:''}]}))}>Add project</Button></section>
 <section id="travel" className="editor-section"><h2>Travel albums</h2><p>Add a destination, position its pin with latitude and longitude, and choose its photos.</p>{content.places.map((place,i)=><div className="entry-edit" key={place.id}><h3>{place.name||`Destination ${i+1}`}</h3><div className="editor-grid"><Field label="City or place" value={place.name} onChange={name=>trip(i,{name})}/><Field label="Country" value={place.country} onChange={country=>trip(i,{country})}/><Field label="Latitude (−85 to 85)" type="number" value={Number.isNaN(place.lat)?'':place.lat} onChange={lat=>trip(i,{lat:lat===''?NaN:Number(lat)})}/><Field label="Longitude (−180 to 180)" type="number" value={Number.isNaN(place.lng)?'':place.lng} onChange={lng=>trip(i,{lng:lng===''?NaN:Number(lng)})}/><Field label="Trip notes" multiline value={place.description} onChange={description=>trip(i,{description})}/></div>{place.photos.map((photo,j)=><div key={photo.src}><PhotoEditor photo={photo} onChange={value=>trip(i,{photos:place.photos.map((p,n)=>n===j?value:p)})}/><Button variant="outline" onClick={()=>trip(i,{photos:place.photos.filter((_,n)=>n!==j)})}>Remove photo {j+1}</Button></div>)}<Upload label="Add trip photos" multiple onBusy={onBusy} onError={setError} onUpload={photos=>setContent(c=>({...c,places:c.places.map((p,n)=>n===i?{...p,photos:[...p.photos,...photos]}:p)}))}/><Button variant="outline" onClick={()=>setContent(c=>({...c,places:c.places.filter((_,n)=>n!==i)}))}>Remove destination</Button></div>)}<Button variant="outline" onClick={()=>setContent(c=>({...c,places:[...c.places,{id:crypto.randomUUID(),name:'',country:'',lat:0,lng:0,description:'',photos:[]}]}))}>Add destination</Button></section></fieldset></div>
}


